name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs at midnight every day
  workflow_dispatch:     # Allows manual triggering

# Set permissions for the GITHUB_TOKEN
permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: ajayrajthakur111
          outputs: |
            dist/github-contribution-grid-snake.svg
            
      - name: Deploy to GitHub Pages (output branch)
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
